apiVersion: mq.iotoperations.azure.com/v1beta1
kind: Broker
metadata:
  name: "broker"
  namespace: default
spec:
  authImage:
    pullPolicy: Always
    repository: e4kpreview.azurecr.io/dmqtt-authentication
    tag: 0.1.0-preview-rc4
  brokerImage:
    pullPolicy: Always
    repository: e4kpreview.azurecr.io/dmqtt-pod
    tag: 0.1.0-preview-rc4
  healthManagerImage:
    pullPolicy: Always
    repository: e4kpreview.azurecr.io/dmqtt-operator
    tag: 0.1.0-preview-rc4
  mode: auto
  encryptInternalTraffic: false # or true, requires cert-manager
  diagnostics:
    probeImage: e4kpreview.azurecr.io/diagnostics-probe:0.1.0-preview-rc4
    diagnosticServiceEndpoint: azedge-diagnostics-service:9700
    enableMetrics: true  
    enableTracing: true  
    logLevel: info,hyper=off,kube_client=off,tower=off,conhash=off,h2=off
    enableSelfCheck: true
---
apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: "listener1883"
  namespace: default
spec:
  serviceType: loadBalancer # or clusterIp
  brokerRef: "broker"
  authenticationEnabled: false
  authorizationEnabled: false
  port: 1883
---
apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: "listener8883"
  namespace: default
spec:
  serviceType: loadBalancer # or clusterIp
  brokerRef: "broker"
  authenticationEnabled: true
  authorizationEnabled: false
  port: 8883
  tls:
    manual:
      secretName: "iotmq-tls-secret"
---
apiVersion: mq.iotoperations.azure.com/v1beta1 
kind: BrokerAuthentication 
metadata: 
  name: "x509-auth-only" 
  namespace: default 
spec: 
  listenerRef: 
    - "listener8883" 
  authenticationMethods: 
    - x509: 
        trustedClientCaCert: client-ca-configmap
        # attributes:
        #   secretName: x509-attributes
---
apiVersion: mq.iotoperations.azure.com/v1beta1
kind: DiagnosticService
metadata:
  name: azedge-diagnostics-service
  namespace: default
spec:
  image:
    pullPolicy: Always
    repository: e4kpreview.azurecr.io/diagnostics-service
    tag: 0.1.0-preview-rc4
  logFormat: "text"